spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/anime?characterEncoding=UTF8
    username: root
    password: y112502


mybatis:
  configuration:
    map-underscore-to-camel-case: true
